// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZWXurY0DGfIWxeKTRvWv6aPohsGIG9OE',
    appId: '1:90304196213:web:79b9e3bf6e262123d4123c',
    messagingSenderId: '90304196213',
    projectId: 'project-kp-fd649',
    authDomain: 'project-kp-fd649.firebaseapp.com',
    storageBucket: 'project-kp-fd649.firebasestorage.app',
    measurementId: 'G-5Z3KJ0ZGMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAXc35a1aaCjdF0CzH7s56_uEHZAj8lys',
    appId: '1:90304196213:android:7915787e125e2ee3d4123c',
    messagingSenderId: '90304196213',
    projectId: 'project-kp-fd649',
    storageBucket: 'project-kp-fd649.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAREuBnO_qcCrbswIMVDrQq5W9Q5NcMinY',
    appId: '1:90304196213:ios:c04b7697d5cd2233d4123c',
    messagingSenderId: '90304196213',
    projectId: 'project-kp-fd649',
    storageBucket: 'project-kp-fd649.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiAbsenOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAREuBnO_qcCrbswIMVDrQq5W9Q5NcMinY',
    appId: '1:90304196213:ios:c04b7697d5cd2233d4123c',
    messagingSenderId: '90304196213',
    projectId: 'project-kp-fd649',
    storageBucket: 'project-kp-fd649.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiAbsenOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZWXurY0DGfIWxeKTRvWv6aPohsGIG9OE',
    appId: '1:90304196213:web:aa8e57773f102042d4123c',
    messagingSenderId: '90304196213',
    projectId: 'project-kp-fd649',
    authDomain: 'project-kp-fd649.firebaseapp.com',
    storageBucket: 'project-kp-fd649.firebasestorage.app',
    measurementId: 'G-080JJP935N',
  );
}
